# Generated by Django 5.1.4 on 2024-12-25 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='packages',
            name='sub_image_1',
        ),
        migrations.AlterField(
            model_name='packages',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='packages',
            name='sub_image_2',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
