# Generated by Django 5.1.4 on 2024-12-25 13:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_remove_packages_sub_image_1_alter_packages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='sub_image_1',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
