# Generated by Django 5.1.4 on 2024-12-26 05:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packages_sub_image_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahPackage_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the Umrah Package', max_length=255)),
                ('description', models.TextField(help_text='Brief overview of the package')),
                ('hero_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('highlights', models.JSONField(default=list)),
                ('duration', models.CharField(help_text="Duration of the package (e.g., '7 days, 6 nights')", max_length=100)),
                ('departure_date', models.DateField(help_text='Departure date for the package')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per person for the package', max_digits=10)),
            ],
        ),
    ]
