# Generated by Django 5.1.3 on 2024-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.CharField(max_length=100)),
                ('contact_sub_title', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('phone', models.CharField(max_length=26)),
                ('location', models.TextField(null=True)),
            ],
        ),
    ]
