# Generated by Django 5.1.3 on 2024-11-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_image_1', models.ImageField(blank=True, null=True, upload_to='logo_images/')),
                ('logo_image_2', models.ImageField(blank=True, null=True, upload_to='logo_images/')),
                ('welcome_title', models.CharField(max_length=100)),
                ('welcome_paragraph', models.CharField(max_length=100)),
            ],
        ),
    ]
