# Generated by Django 5.1.3 on 2024-11-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='welcome_paragraph',
            field=models.CharField(max_length=1000),
        ),
    ]
