# Generated by Django 5.1.3 on 2024-11-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_upcomingtrips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingtrips',
            name='upcoming_title',
        ),
    ]
