# Generated by Django 5.1.3 on 2024-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_upcomingtrips_upcoming_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmrahPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('umrah_package_title', models.CharField(max_length=100)),
                ('umrah_package_sub_title', models.CharField(max_length=100)),
                ('umrah_package_free_text', models.CharField(max_length=100)),
                ('umrah_package_bg_image', models.ImageField(blank=True, null=True, upload_to='umrah_package_bg_images/')),
            ],
        ),
    ]
