# Generated by Django 5.1.3 on 2024-11-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_umrahpackage_umrah_package_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=100)),
                ('about_paragraph', models.CharField(max_length=100)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about_images/')),
            ],
        ),
    ]
