# Generated by Django 5.1.3 on 2024-11-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='about_paragraph',
            field=models.CharField(max_length=600),
        ),
    ]
