# Generated by Django 5.1.3 on 2024-11-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_aboutsection_about_paragraph'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutsection',
            name='about_paragraph',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='about_first_paragraph',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='about_second_paragraph',
            field=models.TextField(null=True),
        ),
    ]
