# Generated by Django 5.1.3 on 2024-11-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_aboutsection_about_paragraph_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_image', models.ImageField(blank=True, null=True, upload_to='destinations_images/')),
                ('destination_name', models.CharField(max_length=100)),
            ],
        ),
    ]
