# Generated by Django 5.1.4 on 2024-12-25 11:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='about_image',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='carsousel',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='destinations',
            name='destination_image',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='logo_image_1',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='logo_image_2',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='umrahpackage',
            name='umrah_package_bg_image',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='upcomingtrips',
            name='package_image',
            field=cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image'),
        ),
    ]
