# Generated by Django 5.1.4 on 2024-12-26 05:11

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_aboutsection_about_image_alter_carsousel_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(default='default_image_placeholder', max_length=255, verbose_name='image')),
            ],
        ),
    ]
