# Generated by Django 5.1.3 on 2024-11-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_page_title', models.CharField(max_length=100)),
                ('about_page_first_paragraph', models.TextField(null=True)),
                ('about_page_second_paragraph', models.TextField(null=True)),
                ('about_page_image_1', models.ImageField(blank=True, null=True, upload_to='about_page_images/')),
                ('our_values_title', models.CharField(max_length=100)),
                ('our_values_sub_title_1', models.CharField(max_length=100)),
                ('our_values_content_1', models.TextField()),
                ('our_values_sub_title_2', models.CharField(max_length=100)),
                ('our_values_content_2', models.TextField()),
                ('our_values_sub_title_3', models.CharField(max_length=100)),
                ('our_values_content_3', models.TextField()),
                ('why_choose_us_title', models.CharField(max_length=100)),
                ('why_choose_us_first_paragraph', models.TextField()),
                ('why_choose_us_second_paragraph', models.TextField()),
                ('about_page_image_2', models.ImageField(blank=True, null=True, upload_to='about_page_images/')),
            ],
        ),
    ]
