# Generated by Django 5.1.3 on 2024-11-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='client_images/')),
                ('client_name', models.CharField(max_length=100)),
                ('client_words', models.TextField(null=True)),
            ],
        ),
    ]
